version: "3"

services:
  wppconnect-server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: wppconnect-server
    container_name: wppconnect-server
    hostname: wppconnect-server
    ports:
      - 21465:21465
    entrypoint: docker-entrypoint.sh yarn dev 
    networks:
      - wpp-network
    tty: true

networks:
  wpp-network:
    driver: bridge
